definitions:
  steps:
    - step: &Build
        name: Build
        image: node:16
        script:
          - npm ci
          - npm run build
    - step: &InstallArc
        name: Install Arc
        image: node:16
        script:
          - npm i -g @architect/architect
    - step: &DeployActingDEV
        name: Deploy acting-dev
        image: node:16
        script:
          - arc deploy --acting-dev --prune          
    - step: &DeployActingQA
        name: Deploy acting-qa
        image: node:16
        script:
          - arc deploy --acting-qa --prune  
    - step: &DeployStaging
        name: Deploy staging
        image: node:16
        script:
          - arc deploy --staging --prune  
    - step: &DeployProduction
        name: Deploy production
        image: node:16
        script:
          - arc deploy --production --prune  

pipelines:
  branches:
    develop:
      - step: *Build
      - step: *InstallArc
      - step:
          <<: *DeployActingDEV
          name: acting-dev
          deployment: acting-dev
          trigger: manual
      - step:
          <<: *DeployActingQA
          name: acting-qa
          deployment: acting-qa
          trigger: manual
    main:
      - step: *DownloadDeps
      - step: *Build
      - step: *InstallArc
      - step:
          <<: *DeployStaging
          name: staging
          deployment: staging
          trigger: manual
      - step:
          <<: *DeployProduction
          name: prod
          deployment: prod
          trigger: manual
