definitions:
  steps:
    - step: &Build
        name: Build
        script:
          - npm i
          - npm run build
    - step: &InstallAWSCLI
        name: Install AWS CLI
        script:
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - ./aws/install
    - step: &InstallArc
        name: Install Arc
        script:
          - npm i -g @architect/architect
    - step: &DeployActingDEV
        name: Deploy acting-dev
        script:
          - npm i
          - npm run build
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - ./aws/install
          - npm i -g @architect/architect
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID         
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - npx arc deploy --staging --prune          
    - step: &DeployStaging
        name: Deploy staging
        script:
          - npx arc deploy name --staging --prune  
    - step: &DeployProduction
        name: Deploy production
        script:
          - npx arc deploy --production --prune  

image: node:16
pipelines:
  branches:
    develop:
      - step: *Build
      - step:
          <<: *DeployActingDEV
          name: acting-dev
          deployment: acting-dev
          trigger: manual
    main:
      - step: *Build
      - step: *InstallAWSCLI
      - step: *InstallArc
      - step:
          <<: *DeployStaging
          name: staging
          deployment: staging
          trigger: manual
      - step:
          <<: *DeployProduction
          name: prod
          deployment: prod
          trigger: manual
