definitions:
  steps:
    - step: &Build
        name: Build
        script:
          - npm i
          - npm run build

    - step: &DeployActingDEV
        name: Deploy acting-dev
        script:
          - npm i -g @architect/architect
          - npx arc deploy --testing --prune          
    - step: &DeployActingQA
        name: Deploy acting-qa
        script:
          - npm i -g @architect/architect
          - npx arc deploy --staging --prune  
    - step: &DeployStaging
        name: Deploy staging
        script:
          - npm i -g @architect/architect
          - npx arc deploy --staging --prune  
    - step: &DeployProduction
        name: Deploy production
        script:
          - npm i -g @architect/architect
          - npx arc deploy --production --prune  

image: node:16
pipelines:
  branches:
    develop:
      - step: *Build
      - step:
          <<: *DeployActingDEV
          name: acting-dev
          deployment: acting-dev
          trigger: manual
      - step:
          <<: *DeployActingQA
          name: acting-qa
          deployment: acting-qa
          trigger: manual
    main:
      - step: *Build
      - step:
          <<: *DeployStaging
          name: staging
          deployment: staging
          trigger: manual
      - step:
          <<: *DeployProduction
          name: prod
          deployment: prod
          trigger: manual
